# Generated by Django 6.0.2 on 2026-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('seller', models.CharField(default='Vendedor Genérico', max_length=100)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('product_dimensions', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
